### ISSUE TITLE
Add Episodes of Podcast to Podcast Page using the RSS feed.

### ISSUE THREAD

**Issue by CharlesC03** [wartimeaide/website#5]
This is so that people who go visit the website can listen to episodes through the website. On the podcast page have a map, where we can put each episode on the map with the corresponding location in discussion with the episode. Also add other links/popups such that you can all episodes and other for potentially interviews. Perhaps a filter for the different types of episodes.

**Comment by GalvinGao** [comment]
Implemented in https://github.com/wartimeaide/website/commit/bc5d2576060c564eac5f724d0861e1a1fceebc29
